id: AD5EFD2D8
title: 'The Jewel Rosary: A Concise Aspiration Towards the Buddhafield of the Blessed
  Akṣobhya'
type: translation
pechas:
- I7457A953
- I3A04054C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:45:57.066612
  last_modified_at: 2023-01-04 11:45:57.066618
  collections:
  - Drimé Zhingkyong Gönpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I7457A953/0B6C: 8F99
  I3A04054C/1C58: 8F99
